#
###################################
# Site wide configuration
####################################
#
title: H-Planet
email: esteepark8@gmail.com
description: Estee's awesome blog powered by jekyll.
url: https://esteepark.github.io/ # the base hostname & protocol for your site
keywords: ["Service Design", "Entrepreneur", "AI"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Korea/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


#
###################################
# Site Owner configuration
####################################
#
owner:
  name: esteepark
  avatar: avatar.png
  job: "Service Designer & Entrepreneur"
  bio: "An entrepreneur who loves technology awesome things. Supporting for young makers education. Korea."
  email: esteepark8@gmail.com
  disqus-shortname: iPlanet
  twitter: esteepark8 #username
  facebook: esteepark8 #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: esteepark #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: esteepark8 #username
  xing: #username
  instagram: esteepark8 #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username

  logo: imaru-logo.png
